name: HyP3 Plugin

on: push

jobs:

  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8  flake8-import-order flake8-blind-except flake8-builtins
    - name: Lint with flake8
      run: |
        flake8 --max-line-length=120 --import-order-style=pycharm --statistics --application-import-names hyp3_geocode


  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Scan for secrets with gitleaks
        uses: zricethezav/gitleaks-action@master


  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install trufflehog gitdb2=="2.*"
      - name: Scan for secrets with trufflehog
        run: |
          export LAST_TAG_HASH=$(git show-ref --hash -- $(git describe --abbrev=0))
          trufflehog --regex --entropy True --since_commit "${LAST_TAG_HASH}" file://"${PWD}"

  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find common python security issues with bandit
        uses: jpetrucciani/bandit-check@master
        with:
          path: 'hyp3_geocode'

